"""Adds Author model

Revision ID: 21389cfd8a32
Revises: 17499b42aeaf
Create Date: 2022-05-09 10:25:30.357991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21389cfd8a32'
down_revision = '17499b42aeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
